<div>
  <h1>ホーム</h1>
  <h3>{$session.userInfo.mailaddress}</h3>
</div>
<div>
  <ul>
    <li>イベント作成</li>
    <li>イベント一覧</li>
  </ul>
  <ul>
    <li>アカウント設定</li>
    <li><a href="/?action_logout=true">ログアウト</a></li>
  </ul>
</div>
<div>
  <h1>ようこそ</h1>
  <ul>
    <li>イベント作成</li>
    <li>イベント一覧</li>
  </ul>
</div>
